/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Roland Mainz, GISBURN@W-Specht.rhein-ruhr.de
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_SOURCE                              0
#define GD_DATATYPE                            1
#define GD_DESTINATION                         2
#define GD_GET_SOURCE                          3
#define GD_GET_DATATYPE                        4
#define GD_GET_DESTINATION                     5
#define GD_CONVERT                             6
#define GD_CANCEL                              7

#define GDX_SOURCE                             0
#define GDX_DATATYPE                           1
#define GDX_DESTINATION                        2
#define GDX_GET_SOURCE                         3
#define GDX_GET_DATATYPE                       4
#define GDX_GET_DESTINATION                    5
#define GDX_CONVERT                            6
#define GDX_CANCEL                             7

#define GD_DATATYPEDT                          0
#define GD_OKDT                                1
#define GD_CANCELDT                            2

#define GDX_DATATYPEDT                         0
#define GDX_OKDT                               1
#define GDX_CANCELDT                           2

#define DTConvert_MAIN_CNT 8
#define DTConvert_DATATYPE_CNT 3

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *DTConvert_MAINWnd;
extern struct Window        *DTConvert_DATATYPEWnd;
extern struct Gadget        *DTConvert_MAINGList;
extern struct Gadget        *DTConvert_DATATYPEGList;
extern UWORD                 DTConvert_MAINZoom[4];
extern UWORD                 DTConvert_DATATYPEZoom[4];
extern struct Gadget        *DTConvert_MAINGadgets[8];
extern struct Gadget        *DTConvert_DATATYPEGadgets[3];
extern UWORD                 DTConvert_MAINLeft;
extern UWORD                 DTConvert_MAINTop;
extern UWORD                 DTConvert_MAINWidth;
extern UWORD                 DTConvert_MAINHeight;
extern UWORD                 DTConvert_DATATYPELeft;
extern UWORD                 DTConvert_DATATYPETop;
extern UWORD                 DTConvert_DATATYPEWidth;
extern UWORD                 DTConvert_DATATYPEHeight;
extern UBYTE                *DTConvert_MAINWdt;
extern UBYTE                *DTConvert_DATATYPEWdt;
extern struct TextAttr      *Font, Attr;
extern UWORD                 FontX, FontY;
extern UWORD                 OffX, OffY;
extern UWORD                 DTConvert_MAINGTypes[];
extern UWORD                 DTConvert_DATATYPEGTypes[];
extern struct NewGadget      DTConvert_MAINNGad[];
extern struct NewGadget      DTConvert_DATATYPENGad[];
extern IPTR                 DTConvert_MAINGTags[];
extern IPTR                 DTConvert_DATATYPEGTags[];


