##begin config
basename AAC
version 41.0
superclass SOUNDDTCLASS
classdatatype struct AAC_Data
##end config
##begin cdefprivate
#include "aacclass.h"
##end cdefprivate
##begin cdef
#include <datatypes/datatypesclass.h>
#include <datatypes/soundclass.h>
##end cdef
##begin methodlist
OM_NEW
OM_DISPOSE
##end methodlist
