##begin config
basename MP3
version 41.1
superclass SOUNDDTCLASS
classdatatype struct MP3_Data
##end config
##begin cdefprivate
#include "mp3class.h"
##end cdefprivate
##begin cdef
#include <datatypes/datatypesclass.h>
#include <datatypes/soundclass.h>
##end cdef
##begin methodlist
OM_NEW
OM_DISPOSE
##end methodlist
